cleaning up function and aliases

diff --git a/function_and_aliases/dot-system_aliases b/function_and_aliases/dot-system_aliases
--- a/function_and_aliases/dot-system_aliases
+++ b/function_and_aliases/dot-system_aliases
@@ -41,12 +41,20 @@ alias e="exit"
 
 # Easier navigation: .., ..., ...., ....., ~ and -
 alias .="cd ."
-alias ..="cd .."
-alias ...="cd ../.."
-alias ....="cd ../../.."
-alias .....="cd ../../../.."
+# Navigation
+alias ..='cd ..'
+alias ...='cd ../..'
+alias .3='cd ../../..'
+alias .4='cd ../../../..'
+alias .5='cd ../../../../..'
+alias ~='cd ~'
+alias -- -='cd -'
 alias cdd='cd -'  # back to last directory
-
+alias 1='cd -'
+alias 2='cd -2'
+alias 3='cd -3'
+alias 4='cd -4'
+alias 5='cd -5'
 
  # enable color support of ls and also add handy aliases
  if [ -x /usr/bin/dircolors  ]; then
@@ -199,5 +207,547 @@ alias tmp='command mkdir --parents --verbose $TMPDIR/$(whoami) && cd $TMPDIR/$(w
  alias bwlogin='bw login --code "$(auth bitwarden)" "$(< .mutt/accounts/com.gmail/email.txt)" "$(gpg --no-tty --quiet --decrypt ~/.bitwarden/secret.gpg)"'
  alias bwunlock='export BW_SESSION="$(bw unlock --raw $(gpg --no-tty --quiet --decrypt ~/.bitwarden/secret.gpg))"'
  alias rsync='rsync --protect-args --compress --verbose --progress --human-readable'
+
+
+
+# Easy report
+alias ls='ls -Fh --color=auto --group-directories-first'
+alias grep='grep --color=auto'
+alias l='ls -l'
+alias la='ls -lA'
+alias lr='ls -R'
+alias lf='ls -l | grep "^-"'
+alias l.f='ls -ld .* | grep "^-"'
+alias ld='ls -l | grep "^d"'
+alias l.d='ls -ld .* | grep "^d"'
+alias dud='du -d 1 -h'
+alias duf='du -sh *'
+alias fdir='find . -type d -name'
+alias ff='find . -type f -name'
+alias h='history'
+alias hgrep='history | grep'
+alias lgrep='ls -l | grep'
+alias lagrep='ls -lA | grep'
+alias sgrep='grep -R -n -H -C 5 --exclude-dir={.git,.svn,.tldr,node_modules,Trash,vendor}'
+alias cp='cp -iv'
+alias mv='mv -iv'
+alias ln='ln -iv'
+alias mkdir='mkdir -v'
+alias rm='rm -i'
+alias rmf='rm -rf'
+alias p='ps axo pid,user,pcpu,comm'
+alias uptime='uptime -p'
+alias free='free -h'
+alias disk='df -h | grep sd \
+    | sed -e "s_/dev/sda[1-9]_\x1b[34m&\x1b[0m_" \
+    | sed -e "s_/dev/sd[b-z][1-9]_\x1b[33m&\x1b[0m_" \
+    | sed -e "s_[,0-9]*[MG]_\x1b[36m&\x1b[0m_" \
+    | sed -e "s_[0-9]*%_\x1b[32m&\x1b[0m_" \
+    | sed -e "s_9[0-9]%_\x1b[31m&\x1b[0m_" \
+    | sed -e "s_/mnt/[-_A-Za-z0-9]*_\x1b[34;1m&\x1b[0m_"'
+alias alu='apt list --upgradable'
+alias preview='fzf --height=50% --layout=reverse --preview="bat --color=always {}"'
+
+# Shortcuts
+alias c='clear'
+alias cat='bat'
+alias ch='echo > ~/.bash_history && echo > ~/.zsh_history'
+alias cz='echo > ~/.z'
+alias e='exit'
+alias htop-user='htop -u "$USER"'
+alias incognito='unset HISTFILE'
+alias ip-address='curl -s -H "Accept: application/json" https://ipinfo.io/json | jq "del(.loc, .postal, .readme)"'
+alias mp3-dl='youtube-dl --ignore-config --extract-audio \
+    --audio-format "mp3" --audio-quality 0 --embed-thumbnail \
+    --add-metadata --metadata-from-title "%(artist)s - %(title)s" \
+    --output "$HOME/Downloads/%(title)s.%(ext)s"'
+alias pbcopy='xclip -selection clipboard'
+alias pbpaste='xclip -selection clipboard -o'
+alias timer='echo "Timer started. Stop with Ctrl-D." && date "+%a, %d %b %H:%M:%S" && time cat && date "+%a, %d %b %H:%M:%S"'
+alias tldr='tldr -t base16'
+
+# Developer shortcuts
+alias g='git'
+alias python='python3'
+alias s='subl'
+alias v='vim'
+
+# Typos
+alias :q='exit'
+alias help='man'
+alias quit='exit'
+
+#######################################################################
+#                               Aliases                               #
+#######################################################################
+# ls aliases
+alias ll='ls -alF'
+alias la='ls -A'
+alias l='ls -CF'
+alias ls='ls --color'
+
+# Backup aliases
+#alias pc2toshibaDocuments='sudo rsync -e "sudo -u cris" -avzh --progress /home/arch/Documents/ /run/media/arch/Toshiba2/Documents'
+#alias pc2toshibaMusic='sudo rsync -e "sudo -u arch" -avzh --delete --progress /home/arch/Music_clean/ /run/media/arch/Toshiba/Music_clean/'
+#alias pc2toshibaPictures='sudo rsync -e "sudo -u arch" -avzh --progress /home/arch/Images/ /run/media/arch/Toshiba2/Pictures/'
+#alias pc2toshibaMail='sudo rsync -e "sudo -u arch" -avzh --progress /home/arch/.mail/ /run/media/arch/Toshiba2/Mail/'
+#alias pc2toshibaVideos='sudo rsync -e "sudo -u cris" -avzh --progress /home/cris/Videos/ /run/media/cris/Toshiba2/Videos/'
+#alias toshiba2pcDocuments='rsync -avzh --delete --progress /run/media/cris/Toshiba2/Clases/ /home/cris/Documents/'
+#alias toshiba2pcMusic='sudo rsync -e "sudo -u arch" -avzh --progress /run/media/arch/Toshiba/Music/ /home/arch/Music/'
+#alias toshiba2pcPictures='rsync -avzh --delete --progress /run/media/cris/Toshiba2/Pictures/ /home/cris/Images/'
+# sudo rsync -e "sudo -u arch" -avzh --progress /run/media/arch/Toshiba2/Clases/Papeles /home/arch/Documents/
+
+#######################################################################
+#                              Shortcuts                              #
+#######################################################################
+
+
+# Turn on nvidia card
+alias bbon='sudo tee /proc/acpi/bbswitch <<< ON'
+
+# Turn off nvidia card
+alias bboff='sudo rmmod nvidia_uvm; sudo rmmod nvidia; sudo tee /proc/acpi/bbswitch <<< OFF;'
+
+# Music suite ncmpcpp
+alias ncm='ncmpcpp'
+
+# Compile latex on background
+alias ltx="grep -l '\\documentclass' *tex | xargs latexmk -pdf -pvc -silent > /dev/null 2>&1 &"
+
+# Unmount disk
+alias udisk='udisksctl unmount -b /dev/sdb1;udisksctl unmount -b /dev/dm-0;udisksctl lock -b /dev/sdb2;udisksctl power-off -b /dev/sdb;'
+
+# Mount disk
+alias mdisk='udisksctl unlock -b /dev/sdb2;udisksctl mount -b /dev/dm-0;'
+
+# Keyboard light up
+alias ledu='sudo ~/.config/i3/leds_up.sh'
+
+# Keyboard light down
+alias ledd='sudo ~/.config/i3/leds_down.sh'
+
+#######################################################################
+#                               Config                                #
+#######################################################################
+#########################
+#  Set text editor vim  #
+#########################
+export EDITOR=vim
+alias vi='vim'
+
+
+######################
+#  Add CUDA to path  #
+######################
+export PATH=/opt/cuda/bin:$PATH
+export LD_LIBRARY_PATH=/opt/cuda/lib64:$LD_LIBRARY_PATH
+
+
+###############
+#  gpg-agent  #
+###############
+# GPG variables
+GPG_TTY=$(tty)
+export GPG_TTY
+
+#############
+#  Termite  #
+#############
+if [[ $TERM == xterm-termite ]]; then
+  . /etc/profile.d/vte.sh
+  __vte_prompt_command
+fi
+
+# Termite change conf
+alias tdark='cp ~/.config/termite/configSolarizedDark ~/.config/termite/config'
+alias tlight='cp ~/.config/termite/configSolarizedLight ~/.config/termite/config'
+alias tgruv='cp ~/.config/termite/configGruv ~/.config/termite/config'
+
+# Compatibility for ssh connection
+export TERM=xterm-256color
+
+
+
+
+############
+#  Others  #
+############
+
+#alias milab='~/go/bin/slack-term -token "$SLACK_MILAB_TOKEN"'
+#alias eig='~/go/bin/slack-term -token "$SLACK_EIG_TOKEN"'
+#alias graf='grafana-server --config=/home/arch/.config/grafana/grafana.ini --homepath=/usr/share/grafana'
+
+export PATH=/home/arch/.local/bin:$PATH
+
+# Use bash-completion, if available
+#[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
+#    . /usr/share/bash-completion/bash_completion
+
+# ALIASES
+
+alias Ac='sudo apt autoclean'
+alias Ag='sudo apt install'
+alias Ai='apt show'
+alias Ar='sudo apt remove'
+alias Arm='sudo apt autoremove'
+alias Arp='sudo apt remove --purge'
+alias As='apt search'
+alias VU='~/.vim/update.sh'
+alias ZL='vi ~/.zshlocal ~/.zshrc && ZR'
+alias ZR='echo "Restarting zsh..." && exec zsh -l'
+alias ZU='~/.dotfiles/install.zsh && ZR'
+alias ZshInstall='~/.dotfiles/install.zsh && ZR'
+alias ZshRehash='. ~/.zshrc'
+alias aag='agg'
+alias agg='_agg () { rg --group $@ | less }; _agg'
+alias bc='bc -l'
+alias co='git checkout'
+alias cr2lf="perl -pi -e 's/\x0d/\x0a/gs'"
+alias curltime='curl -w "@$HOME/.curl-format" -o /dev/null -s'
+alias d='docker'
+alias dc='docker-compose'
+alias dls='dpkg -L'
+alias dotenv="eval \$(egrep -v '^#' .env | xargs)"
+alias dsl='dpkg -l | grep -i'
+alias dud='du -sh -- * | sort -h'
+alias e='emacs'
+alias ec='emacsclient --no-wait'
+alias f1="awk '{print \$1}'"
+alias f2="awk '{print \$2}'"
+alias f2k9='f2k -9'
+alias f2k='f2 | xargs -t kill'
+alias f='fg'
+alias fixssh='eval $(tmux showenv -s SSH_AUTH_SOCK)'
+alias g='git'
+alias gA='git add --all :/'
+alias ga='git add'
+alias gaa='gA ; st'
+alias gac='git add `git status -uall | egrep "#\tboth modified:" | cut -d: -f2`'
+alias gap='clear; git add --all --patch'
+alias gb='git branch'
+alias gbd='git branch -d'
+alias gbl='git branch -v -a'
+alias gca='git commit --amend'
+alias gcane='git commit --amend --no-edit'
+alias gcanes='gcane --gpg-sign'
+alias gcanoe='gcne'
+alias gcanoes='gcne --gpg-sign'
+alias gcanv='git commit --amend --no-verify -m'
+alias gcia='git commit --amend'
+alias gcnv='git commit --no-verify -m'
+alias gd='git diff'
+alias gdc='git diff --cached'
+alias gdd='git difftool'
+alias gdt='git difftool'
+alias gdw='git diff -w'
+alias gf='git fetch'
+alias gfa='git fetch --all'
+alias gfmom='git fetch origin && git merge origin/master'
+alias gfrb='git fetch origin && git rebase origin/master'
+alias gfrbi='gfrb --interactive'
+alias gg='git grep'
+alias gh='git stash'
+alias ghl='git stash list'
+alias ghp='git stash pop'
+alias ghs='git stash save'
+alias ghsp='git stash save --patch'
+alias ghw='git stash show -p'
+alias gist='gist -p -c'
+alias gk='gitk &>/dev/null'
+alias gl1='git log -n 1'
+alias gl='git quicklog -n 20'
+alias gll='git quicklog-long'
+alias gls='git log --show-signature'
+alias gmom='git merge origin/master'
+alias gmt='git mergetool'
+alias gp='git push'
+alias gpgdecrypt='gpg --decrypt-files'
+alias gpgencrypt='gpg --default-recipient-self --armor --encrypt-files'
+alias gph='git push heroku'
+alias gpo='git push origin'
+alias gpof='git push origin --force-with-lease'
+alias gpot='git push origin --tags'
+alias grb='git rebase'
+alias grbc='git rebase --continue'
+alias grbi='git rebase -i'
+alias grbil='git rebase -i HEAD~10'
+alias grbs='git rebase --skip'
+alias gs='git show -p'
+alias gsm='git submodule'
+alias gsmu='git submodule update --init --recursive'
+alias gu='git unstage'
+alias gup='git up'
+alias gus='git unstage'
+alias gvc='vim `git diff --name-only --diff-filter=U`'
+alias gvm='vim `git diff --name-only --diff-filter=M`'
+alias i4='sed "s/^/    /"'
+alias icat='lsbom -f -l -s -pf'
+alias iinstall='sudo installer -target / -pkg'
+alias ils='ls /var/db/receipts/'
+alias ishow='pkgutil --files'
+alias k='tree -h'
+alias l="ls -lh"
+alias ll="l -a"
+alias lt='ls -lt'
+alias ltr='ls -ltr'
+alias ndu='node --debug-brk =nodeunit'
+alias nerdcrap='cat /dev/urandom | xxd | grep --color=never --line-buffered "be ef"'
+alias netwhat='lsof -i +c 40'
+alias nmu='nodemon =nodeunit'
+alias notifydone='terminal-notifier -message Done.'
+alias pt='pstree -pul'
+alias px='pilot-xfer -i'
+alias rake='noglob rake'
+alias randpass="LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24 ; echo"
+alias rgg='_rgg () { rg --color always --heading $@ | less }; _rgg'
+alias ri='ri -f ansi'
+alias rls='screen -ls'
+alias rrg='rgg'
+alias rsync-usual='rsync -azv -e ssh --delete --progress'
+alias rxvt-invert="echo -n '[?5t'"
+alias rxvt-scrollbar="echo -n '[?30t'"
+alias scp='scp -C -p'
+alias screen='screen -U'
+alias slurp='wget -t 5 -c -nH -r -k -p -N --no-parent'
+alias sshx='ssh -C -c blowfish -X'
+alias st='git status'
+alias stt='git status -uall'
+alias t='tmux attach'
+alias tree="tree -F -A -I CVS"
+alias tt='tail -n 9999'
+alias vb=VBoxManage
+alias vh=VBoxHeadless
+alias wgetdir='wget -r -l1 -P035 -nd --no-parent'
+alias whois='whois -h geektools.com'
+alias y='yarn'
+alias ye='yarn exec'
+alias x='screen -A -x'
+alias xxx='histring "XXX.*" -c green -s bold'
+
+# Interactive/verbose commands.
+alias mv='mv -i'
+for c in cp rm chmod chown rename; do
+  alias $c="$c -v"
+done
+
+# Make sure vim/vi always gets us an editor.
+#if _has vim; then
+#  alias vi=vim
+#  vs() { vim +"NERDTree $1" }
+#  gvs() { gvim +"NERDTree $1" }
+#else
+#  alias vim=vi
+#fi
+
+#if ! _has gvim && _is Darwin; then
+#  alias gvim='open -a "MacVim"'
+#fi
+
+#if _has rg; then
+#  alias rg='rg --colors path:fg:green --colors match:fg:red'
+#  alias ag=rg
+#  alias ack=rg
+#elif _has ag; then
+#  alias ack=ag
+#  alias ag='ag --color-path 1\;31 --color-match 1\;32 --color'
+#elif _has ack; then
+#  if ! _color; then
+#    alias ack='ack --nocolor'
+#  fi
+#fi
+
+# Move-to-trash command for Gnome. `brew install trash` for one on macOS.
+#if ! _has trash && _has gio; then
+#  alias trash='gio trash'
+#fi
+
+# macOS-like open command for linux
+#if ! _has open && _has xdg-open; then
+#  alias open=xdg-open
+#fi
+
+# Humanize disk space if possible
+#if _try df -H ~; then
+#  alias df='df -H'
+#elif _try df -h ~; then
+#  alias df='df -h'
+#fi
+
+# Nico is amazing for showing me this.
+#alias v='vim -R -'
+#for i in /usr/share/vim/vim*/macros/less.sh(N) ; do
+#  alias v="$i"
+#done
+
+# Linux should definitely have Gnu coreutils, right?
+#if _is Linux; then
+#  if _color && _try ls --color; then
+#    alias ls='ls --color'
+#  fi
+#fi
+
+#if _is Darwin; then
+#  alias strace='sudo dtruss -f sudo -u $USER'
+#fi
+
+# FUNCTIONS {{{1
+
+ya() {
+  for pkg in $@; do
+    yarn add $pkg
+    yarn add -D @types/$pkg &>/dev/null || echo "No separate types for $pkg"
+  done
+}
+
+yr() {
+  for pkg in $@; do
+    yarn remove $pkg
+    yarn remove -D @types/$pkg &>/dev/null
+  done
+}
+
+# ack is really useful. I usually look for code and then edit all of the files
+# containing that code. Changing `ack' to `vack' does this for me.
+#if _has rg; then
+#  vack() {
+#    vim `rg --color=never -l $@`
+#  }
+#elif _has ag; then
+#  vack() {
+#    vim `ag --nocolor -l $@`
+#  }
+#else
+#  vack() {
+#    vim `ack -l $@`
+#  }
+#fi
+#alias vag=vack
+#alias vrg=vack
+
+# ..same thing with gg.
+vgg() {
+  vim `gg -l $@`
+}
+
+# Quick commands to sync CWD between terminals.
+pin() {
+  rm -f ~/.pindir
+  echo $PWD >~/.pindir
+  chmod 0600 ~/.pindir &>/dev/null
+}
+pout() {
+  cd `cat ~/.pindir`
+}
+
+# A quick grep-for-processes.
+psl() {
+  if _is SunOS; then
+    ps -Af | grep -i $1 | grep -v grep
+  else
+    ps auxww | grep -i $1 | grep -v grep
+  fi
+}
+
+# Make a new command.
+vix() {
+  if [ -z "$1" ]; then
+    echo "usage: $0 <newfilename>"
+    return 1
+  fi
+  if [ ! -e "$1" ]; then
+    echo -e "#!/usr/bin/env bash\n\nset -eo pipefail\n" > "$1"
+  fi
+  chmod -v 0755 "$1"
+  vim -c 'normal Go' "$1"
+}
+
+# Make a new command in ~/bin
+makecommand() {
+  if [ -z "$1" ]; then
+    echo "Command name required" >&2
+    return 1
+  fi
+
+  mkdir -p ~/bin
+  local cmd=~/bin/$1
+  if [ -e $cmd ]; then
+    echo "Command $1 already exists" >&2
+  else
+    if [ -z "$2" ]; then
+      echo -e "#!/usr/bin/env bash\n\nset -eo pipefail\n" >$cmd
+    else
+      echo "#!/usr/bin/env $2" >$cmd
+    fi
+  fi
+
+  vix $cmd
+}
+
+# View a Python module in Vim.
+vipy() {
+  p=`python -c "import $1; print $1.__file__.replace('.pyc','.py')"`
+  if [ $? = 0 ]; then
+    vi -R "$p"
+  fi
+  # errors will be printed by python
+}
+
+rxvt-title() {
+  echo -n "]2;$*"
+}
+
+screen-title() {
+  echo -n "k$*\\"
+}
+
+# Everything Git-related
+
+# Commit what's been staged, use args as message.
+#gc() {
+# git commit -m "$*" && \
+#  git log --oneline --decorate -n 10
+#}
+
+# Commit everything, use args as message.
+sci() {
+  if [ $# = 0 ]; then
+    echo "usage: $0 message..." >&2
+    return 1
+  fi
+  git add -A && \
+  hr staging && \
+  git status && \
+  hr committing && \
+  git cim "$*" && \
+  hr results && \
+  git quicklog && \
+  hr done
+}
+
+# Networking. IP address, dig, DNS
+alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
+alias dig="dig +nocmd any +multiline +noall +answer"
+
+# View HTTP traffic
+alias sniff="sudo ngrep -W byline -d 'en0' -t '^(GET|POST) ' 'tcp and port 80'"
+alias httpdump="sudo tcpdump -i en0 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""
+
+# Enhanced WHOIS lookups
+alias whois="whois -h whois-servers.net"
+
+# Download file and save it with filename of remote file
+alias get="curl -O -L"
+
+# Recursively delete `.DS_Store` files
+alias cleanup_dsstore="find . -name '*.DS_Store' -type f -ls -delete"
+
+# Disc utils
+alias diskspace_report="df -P -kHl"
+alias free_diskspace_report="diskspace_report"
+
+# Empty the Trash on all mounted volumes and the main HDD.
+# Also, clear Apple’s System Logs & the useless sleepimage to improve shell startup speed
+#alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo grm -rf $HOME/.Trash; sudo rm -rtv /private/var/log/asl/*.asl; sudo rm /private/var/vm/sleepimage"
+
 
 
